name: threestation
channels:
    - conda-forge
dependencies:
    - astropy
    - bottleneck
    - h5py
    - jupyterlab
    - matplotlib
    - numpy
    - obspy
    - pyproj
    - pyyaml
    - scipy
    - setuptools
    - tqdm
